export * from "./structures/Client";
export * from "./structures/Command";
export * from "./structures/Context";
export * from "./structures/Event";
export * from "./structures/Argument";
export * from "./handlers/CommandHandler";
export * from "./handlers/EventHandler";
export * from "./handlers/Deployer";
export * from "./types";
export * from "./utils/Logger";
export const version = "[VI]{{version}}[/VI]";
