name: Push Code

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js (with npm cache)
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "25"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Check Compatibility
        run: npm run check

  release:
    needs: lint
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup Node.js (with npm cache)
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "25"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Install git-cliff
        uses: taiki-e/install-action@git-cliff

      - name: Run github release script
        run: npm run release:git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
